# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_list',
            field=models.SmallIntegerField(choices=[(0, 'Python'), (1, 'Linux基础'), (2, '前端'), (4, 'Python进阶'), (5, 'UI'), (6, '工具')], default=0),
        ),
    ]
