# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180926_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_list',
            new_name='course_name',
        ),
    ]
